### ISSUE TITLE
Provisioning error

### ISSUE THREAD

**Issue by maccovey** [jhoelzl/vagrant-magento-setup#1]
Hi,
I've got errors during vagrant up.
how can I fix them?

==> default: Writing lock file
==> default: Generating autoload files
==> default: Set correct Permissions
==> default: Remove obsolete Files
==> default: Install Magento CE
==> default:
==> default: FAILED
==> default: ERROR: You should provide the value for --license_agreement_accepted parameter
==> default: ERROR: You should provide the value for --locale parameter
==> default: ERROR: You should provide the value for --timezone parameter
==> default: ERROR: You should provide the value for --default_currency parameter
==> default: ERROR: You should provide the value for --db_host parameter
==> default: ERROR: You should provide the value for --db_name parameter
==> default: ERROR: You should provide the value for --db_user parameter
==> default: ERROR: You should provide the value for --url parameter
==> default: ERROR: You should provide the value for --use_rewrites parameter
==> default: ERROR: You should provide the value for --use_secure parameter
==> default: ERROR: You should provide the value for --secure_base_url parameter
==> default: ERROR: You should provide the value for --use_secure_admin parameter
==> default: ERROR: You should provide the value for --admin_lastname parameter
==> default: ERROR: You should provide the value for --admin_firstname parameter
==> default: ERROR: You should provide the value for --admin_email parameter
==> default: ERROR: You should provide the value for --admin_username parameter
==> default: ERROR: You should provide the value for --admin_password parameter
==> default: /tmp/vagrant-shell: line 173: --license_agreement_accepted: command not found
==> default: /tmp/vagrant-shell: line 175: --locale: command not found
==> default: /tmp/vagrant-shell: line 177: --timezone: command not found
==> default: /tmp/vagrant-shell: line 179: --default_currency: command not found
==> default: /tmp/vagrant-shell: line 181: --db_host: command not found
==> default: /tmp/vagrant-shell: line 183: --db_name: command not found
==> default: /tmp/vagrant-shell: line 185: --db_user: command not found
==> default: /tmp/vagrant-shell: line 187: --db_pass: command not found
==> default: /tmp/vagrant-shell: line 189: --db_prefix: command not found
==> default: /tmp/vagrant-shell: line 191: --session_save: command not found
==> default: /tmp/vagrant-shell: line 193: --admin_frontname: command not found
==> default: /tmp/vagrant-shell: line 195: --url: command not found
==> default: /tmp/vagrant-shell: line 197: --use_rewrites: command not found
==> default: /tmp/vagrant-shell: line 199: --use_secure: command not found
==> default: /tmp/vagrant-shell: line 201: --secure_base_url: command not found
==> default: /tmp/vagrant-shell: line 203: --use_secure_admin: command not found
==> default: /tmp/vagrant-shell: line 205: --admin_firstname: command not found
==> default: /tmp/vagrant-shell: line 207: --admin_lastname: command not found
==> default: /tmp/vagrant-shell: line 209: --admin_email: command not found
==> default: /tmp/vagrant-shell: line 211: --admin_username: command not found
==> default: /tmp/vagrant-shell: line 213: --admin_password: command not found
==> default: /tmp/vagrant-shell: line 215: --encryption_key: command not found
==> default: Adjust URLs and Reindex
==> default: ERROR
==> default:  1146 (42S02) at line 1: Table 'magento.core_config_data' doesn't exist
==> default: Could not open input file: shell/indexer.php
==> default: Finished provisioning.

**Comment by jhoelzl** [comment]
Hi maccovey,

the problem is, that the magento composer package is download, but when it is deployed into the magento folder not all files are copied. I tried several magento repositories, every time the same error. Some files (e.g. app/Mage.php or .htaccess) are not deployed, after this the deployment process stops and therefore the magenta setup through command line fails. You can prevent this, by copying the magento core files from the vendor folder manually into the folder vagrant/magento.

However, i should go back to the code where the magento core files are not installed by composer but through a download from magentocommerce.com. I can make this torrorow, if you can wait... :)

**Comment by maccovey** [comment]
Aha, thank you for the explanation. It's composer's fail.
Sure I can wait. I thought only me experiencing problems with it :)

**Comment by jhoelzl** [comment]
Please checkout the latest commit, it should work now.
